[2025-06-25T13:11:32.769+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-25T13:11:32.839+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sync_ds.sync_ds manual__2025-06-25T13:11:26.125725+00:00 [queued]>
[2025-06-25T13:11:32.861+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sync_ds.sync_ds manual__2025-06-25T13:11:26.125725+00:00 [queued]>
[2025-06-25T13:11:32.862+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-06-25T13:11:32.898+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): sync_ds> on 2025-06-25 13:11:26.125725+00:00
[2025-06-25T13:11:32.917+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-25T13:11:32.922+0000] {standard_task_runner.py:72} INFO - Started process 91 to run task
[2025-06-25T13:11:32.924+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sync_ds', 'sync_ds', 'manual__2025-06-25T13:11:26.125725+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_ds_etl.py', '--cfg-path', '/tmp/tmp37chcs9m']
[2025-06-25T13:11:32.930+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask sync_ds
[2025-06-25T13:11:33.108+0000] {task_command.py:467} INFO - Running <TaskInstance: sync_ds.sync_ds manual__2025-06-25T13:11:26.125725+00:00 [running]> on host 529bcb6b4446
[2025-06-25T13:11:33.468+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='maxp' AIRFLOW_CTX_DAG_ID='sync_ds' AIRFLOW_CTX_TASK_ID='sync_ds' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T13:11:26.125725+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T13:11:26.125725+00:00'
[2025-06-25T13:11:33.474+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-25T13:11:33.526+0000] {log.py:232} WARNING - 2025-06-25 13:11:33,525 [INFO] etl.stages: === Начало процесса синхронизации DS ===
[2025-06-25T13:11:33.525+0000] {stages.py:119} INFO - === Начало процесса синхронизации DS ===
[2025-06-25T13:11:33.528+0000] {log.py:232} WARNING - 2025-06-25 13:11:33,528 [INFO] etl.stages: Начало: 2025-06-25 13:11:33
[2025-06-25T13:11:33.528+0000] {stages.py:121} INFO - Начало: 2025-06-25 13:11:33
[2025-06-25T13:11:38.530+0000] {log.py:232} WARNING - 2025-06-25 13:11:38,530 [INFO] db_utils.check_postges: Проверка/создание БД 'project', схемы 'ds', и таблиц из 'db_utils/ds_tables.sql'
[2025-06-25T13:11:38.530+0000] {check_postges.py:63} INFO - Проверка/создание БД 'project', схемы 'ds', и таблиц из 'db_utils/ds_tables.sql'
[2025-06-25T13:11:38.534+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_ds_etl.py", line 25, in run_sync_ds_tables
    sync_ds_tables(
  File "/opt/airflow/etl/stages.py", line 124, in sync_ds_tables
    prepare_db(db_name, schema_name, sql_filename)
  File "/opt/airflow/db_utils/check_postges.py", line 64, in prepare_db
    create_database(db_name)
  File "/opt/airflow/db_utils/check_postges.py", line 8, in create_database
    conn = get_postgres_properties(db_name='postgres')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/db_utils/postgres_client.py", line 6, in get_postgres_properties
    return psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "db" (172.19.0.2), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-06-25T13:11:38.590+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=sync_ds, task_id=sync_ds, run_id=manual__2025-06-25T13:11:26.125725+00:00, execution_date=20250625T131126, start_date=20250625T131132, end_date=20250625T131138
[2025-06-25T13:11:38.645+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-25T13:11:38.646+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task sync_ds (connection to server at "db" (172.19.0.2), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 91)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_ds_etl.py", line 25, in run_sync_ds_tables
    sync_ds_tables(
  File "/opt/airflow/etl/stages.py", line 124, in sync_ds_tables
    prepare_db(db_name, schema_name, sql_filename)
  File "/opt/airflow/db_utils/check_postges.py", line 64, in prepare_db
    create_database(db_name)
  File "/opt/airflow/db_utils/check_postges.py", line 8, in create_database
    conn = get_postgres_properties(db_name='postgres')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/db_utils/postgres_client.py", line 6, in get_postgres_properties
    return psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "db" (172.19.0.2), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-06-25T13:11:38.730+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-25T13:11:38.800+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-25T13:11:38.804+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
